# Generated by Django 5.0.1 on 2024-03-01 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taksmodel',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
