# Generated by Django 5.0.1 on 2024-03-01 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0003_alter_taksmodel_is_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taksmodel',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
